name: Run Unit Tests

on:
  push:
    branches:
      - task-2
  pull_request:
    branches:
      - task-2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Update to match your Python version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y libta-lib0-dev
          sudo apt-get install -y wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib && ./configure --prefix=/usr && make && sudo make install

      - name: Print Python Version
        run: python --version
      
      - name: Print Installed Packages
        run: pip freeze
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_EXTRA_INDEX_URL: https://pypi.org/simple

      - name: Run tests
        run: |
          python -m unittest discover -s tests  